<?php
$page = [
  'title' => 'Guides | FinOpsWay',
  'description' => 'Practical guides to Databricks cost visibility and compute monitoring.',
  'path' => '/guides/',
  'og_title' => 'Databricks Cost Optimization Guides | FinOpsWay',
  'og_description' => 'Practical Databricks cost optimization guides for cluster monitoring, compute governance and cost transparency.',
  'twitter_description' => 'Practical Databricks cost optimization guides for cluster monitoring and cost transparency.',
  'image' => 'https://finopsway.com/guides/all-purpose-cluster-monitoring/images/original_1.jpg',
  'image_alt' => 'Databricks all-purpose cluster cost monitoring',
  'json_ld' => <<<'JSON'
{"@context":"https://schema.org","@type":"CollectionPage","name":"Databricks Cost Optimization Guides","description":"Practical Databricks cost optimization guides for cluster monitoring, compute governance and cost transparency.","url":"https://finopsway.com/guides/","isPartOf":{"@type":"WebSite","name":"FinOpsWay","url":"https://finopsway.com/"},"mainEntity":{"@type":"ItemList","itemListElement":[{"@type":"ListItem","position":1,"url":"https://finopsway.com/guides/databricks-apps-start-stop/","name":"Cut Databricks Apps costs with scheduled start and stop"},{"@type":"ListItem","position":2,"url":"https://finopsway.com/guides/databricks-genie-cost-control/","name":"Databricks Genie cost control: budgets and usage blocks"},{"@type":"ListItem","position":3,"url":"https://finopsway.com/guides/all-purpose-cluster-monitoring/","name":"Databricks cost optimization: monitoring all-purpose clusters with the API"},{"@type":"ListItem","position":4,"url":"https://finopsway.com/guides/databricks-cost-transparency/","name":"Databricks cost transparency without exposing SQL"}]}}
JSON,
];
include __DIR__ . '/../includes/header.php';
?>
  <main id="main" class="articles-page">
    <section class="articles-hero"><p class="eyebrow">FinOpsWay guides</p><h1>Practical Databricks cost guides</h1><p>Clear ways to find waste, explain it and take action in the workspace.</p></section>
    <section class="article-list" aria-label="Guides"><article class="article-card"><img src="./databricks-apps-start-stop/images/image_1.jpg" width="455" height="380" alt="Databricks Apps scheduled start and stop thumbnail." /><div class="article-card-copy"><p class="eyebrow">Apps cost control</p><h2><a href="./databricks-apps-start-stop/">Cut Databricks Apps costs with scheduled start and stop</a></h2><p>Start Apps before business hours and stop them when they are no longer needed.</p><a class="text-link" href="./databricks-apps-start-stop/">Read guide <span aria-hidden="true">→</span></a></div></article><article class="article-card"><img src="./databricks-genie-cost-control/images/image_1.jpg" width="455" height="380" alt="Databricks Genie cost control thumbnail." /><div class="article-card-copy"><p class="eyebrow">Genie cost control</p><h2><a href="./databricks-genie-cost-control/">Databricks Genie cost control: budgets and usage blocks</a></h2><p>Set a Genie budget, block usage at the threshold and review spend by user.</p><a class="text-link" href="./databricks-genie-cost-control/">Read guide <span aria-hidden="true">→</span></a></div></article><article class="article-card"><img src="./all-purpose-cluster-monitoring/images/original_1.jpg" width="1179" height="800" alt="Original diagram comparing all-purpose and jobs compute costs." /><div class="article-card-copy"><p class="eyebrow">Cluster monitoring</p><h2><a href="./all-purpose-cluster-monitoring/">Databricks cost optimization: monitoring all-purpose clusters with the API</a></h2><p>Find scheduled work that keeps an all-purpose cluster running after the task has finished.</p><a class="text-link" href="./all-purpose-cluster-monitoring/">Read guide <span aria-hidden="true">→</span></a></div></article><article class="article-card"><img src="./databricks-cost-transparency/images/original_1.jpg" width="800" height="678" alt="A visual about making Databricks cost data available to employees." /><div class="article-card-copy"><p class="eyebrow">Cost transparency</p><h2><a href="./databricks-cost-transparency/">Databricks cost transparency without exposing SQL</a></h2><p>Give engineers useful cost signals while keeping query text protected by default.</p><a class="text-link" href="./databricks-cost-transparency/">Read guide <span aria-hidden="true">→</span></a></div></article></section>
  </main>
<?php include __DIR__ . '/../includes/footer.php'; ?>
